import torch

# General
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
SEED = 42

# Paths
DATA_DIR = "data/"
CHECKPOINTS_DIR = "checkpoints/"

# Captioning
CAPTION_EMBED_SIZE = 256
CAPTION_HIDDEN_SIZE = 256
CAPTION_NUM_LAYERS = 1
CAPTION_LEARNING_RATE = 3e-4
CAPTION_BATCH_SIZE = 32
CAPTION_NUM_EPOCHS = 10

# Classification
CLASSIFICATION_ARCH = "resnet34"
CLASSIFICATION_HIDDEN_UNITS = 512
CLASSIFICATION_LEARNING_RATE = 0.001
CLASSIFICATION_BATCH_SIZE = 64
CLASSIFICATION_NUM_EPOCHS = 20

# Generation
GENERATION_ITERATIONS = 500
GENERATION_LEARNING_RATE = 1e-2
